name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run build
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
          CNAME: experiment-on.me